export const SHOW_EMP_LIST = 'SHOW_EMP_LIST';
export const ADD_PERSONAL_INFO = 'ADD_PERSONAL_INFO';
export const SHOW_PSERSONAL_INFO = 'SHOW_PSERSONAL_INFO';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';
export const SHOW_EXPERIENCE = 'SHOW_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const ADD_SKILLS = 'ADD_SKILLS';
export const SHOW_SKILLS = 'SHOW_SKILLS';
export const DELETE_SKILLS = 'DELETE_SKILLS';
export const UPDATE_SKILLS = 'UPDATE_SKILLS';


export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const CLEAR = 'CLEAR';

export const BIND_EMPLOYEE_DETAILS = 'BIND_EMPLOYEE_DETAILS';
export const SHOW_EMPLOYEE_DETAILS = 'SHOW_EMPLOYEE_DETAILS';