export const SHOW_EMP_LIST = 'SHOW_EMP_LIST';
export const ADD_PERSONAL_INFO = 'ADD_PERSONAL_INFO';
export const SHOW_PSERSONAL_INFO = 'SHOW_PSERSONAL_INFO';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const SHOW_EXPERIENCE = 'SHOW_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';